services:
  mosquitto:
    build:
      context: ${MOSQUITTO_CONTEXT}
      dockerfile: ${MOSQUITTO_DOCKERFILE}
    image: ${MOSQUITTO_IMAGE}
    container_name: ${MOSQUITTO_CONTAINER}
    ports:
      - "${MOSQUITTO_PORTS_1}"
      - "${MOSQUITTO_PORTS_2}"
    restart: always

  backend:
    build:
      context: ${BACKEND_CONTEXT}
      dockerfile: ${BACKEND_DOCKERFILE}
    image: ${BACKEND_IMAGE}
    container_name: ${BACKEND_CONTAINER}
    depends_on:
      - mosquitto
    restart: always

  webapp:
    build:
      context: ${WEBAPP_CONTEXT}
      dockerfile: ${WEBAPP_DOCKERFILE}
    image: ${WEBAPP_IMAGE}
    container_name: ${WEBAPP_CONTAINER}
    depends_on:
      - mosquitto
      - backend
    ports:
      - "${WEBAPP_PORTS}"
    restart: always

  database:
    build:
      context: ./DataBase
      dockerfile: Dockerfile
    image: postgres_image
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: iot
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: