version: '3.8'

services:
  mosquitto:
    build:
      context: ./Mosquitto-MQTT
      dockerfile: Dockerfile
    container_name: mosquitto_container
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always

  webapp:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    container_name: webapp_container
    depends_on:
      - mosquitto
    ports:
      - "80:80"
    restart: always
