CREATE TABLE USUARIO (
    ID SERIAL NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    SENHA VARCHAR NOT NULL,
    NOME VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SALA (
    ID SERIAL NOT NULL,
    ID_CRIADOR INTEGER NOT NULL,
    NOME VARCHAR NOT NULL,
    ESTADO VARCHAR(10) NOT NULL DEFAULT 'AUTOMATICO',
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CRIADOR) REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT ESTADO_VALIDO CHECK (ESTADO IN ('ACENDER', 'AUTOMATICO', 'APAGAR'))
);

CREATE TABLE INSCRICAO (
    ID SERIAL NOT NULL,
    ID_SALA INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_SALA) REFERENCES SALA (ID) ON DELETE CASCADE,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO (ID) ON DELETE CASCADE
);

CREATE TABLE SENSOR (
    ID SERIAL NOT NULL,
    ID_SALA INTEGER NOT NULL,
    TIPO VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_SALA) REFERENCES SALA (ID) ON DELETE CASCADE,
    CONSTRAINT TIPO_SENSOR_CHECK CHECK (TIPO IN ('CORRENTE', 'TENSAO', 'PRESENCA'))
);

CREATE TABLE MEDIDA (
    ID SERIAL NOT NULL,
    ID_SALA INTEGER NOT NULL,
    VALOR DOUBLE PRECISION NOT NULL,
    HORARIO TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_SALA) REFERENCES SALA (ID) ON DELETE CASCADE
);
