CREATE TABLE USUARIO (
    ID SERIAL NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    SENHA VARCHAR NOT NULL,
    NOME VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SALA (
    ID SERIAL NOT NULL,
    ID_CRIADOR INTEGER NOT NULL,
    NOME VARCHAR NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_CRIADOR) REFERENCES USUARIO (ID)
);

CREATE TABLE INSCRICAO (
    ID SERIAL NOT NULL,
    ID_SALA INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_SALA) REFERENCES SALA (ID),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO (ID)
);

CREATE TABLE SENSOR (
    ID SERIAL NOT NULL,
    ID_SALA INTEGER NOT NULL,
    TIPO VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_SALA) REFERENCES SALA (ID),
    CONSTRAINT TIPO_SENSOR_CHECK CHECK (TIPO IN ('CORRENTE', 'TENSAO', 'PRESENCA'))
);

CREATE TABLE MEDIDA (
    ID SERIAL NOT NULL,
    ID_SALA INTEGER NOT NULL,
    VALOR DOUBLE PRECISION NOT NULL,
    HORARIO TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_SALA) REFERENCES SALA (ID)
);